data_ingestion:
  raw_data_path: "data/raw/uber.csv"
  test_size: 0.2
  random_state: 42

data_preprocessing:
  test_size: 0.2
  random_state: 42

feature_engineering:
  features: ["dist_km", "hour", "day", "month", "year", "dayofweek", "passenger_count"]
  target: "fare_amount"

model_building:
  max_depth: 10
  max_leaf_nodes: 32
  random_state: 10
