name: Uber Fare CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --system -r requirements.txt
          uv pip install --system "dvc[s3]" dagshub mlflow uvicorn fastapi pytest httpx python-multipart

      - name: DVC Remote Setup
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          dvc remote add -d storage s3://dvc
          dvc remote modify storage endpointurl https://dagshub.com/RedLordezh7Venom/uberfareMLOPs.s3
          dvc remote modify storage access_key_id ${{ secrets.CAPSTONE_TEST }}
          dvc remote modify storage secret_access_key ${{ secrets.CAPSTONE_TEST }}

      - name: Pull Data from DVC Remote
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          dvc pull
          
      - name: Run DVC Pipeline
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          dvc repro

      - name: Run Model Registry Promotion
        if: success()
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          python -m src.models.register_model

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t uber-fare-app:latest .

      - name: AWS Authentication & ECR Push
        if: github.ref == 'refs/heads/main'
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          docker tag uber-fare-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to EKS
        if: github.ref == 'refs/heads/main'
        uses: azure/setup-kubectl@v3
      - run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name uber-fare-cluster
          kubectl apply -f deployment.yaml
